import type { DeliveryPlanItemStatus } from "@prisma/client";
import { prisma, type Db } from "../db";
import { lineTotalMinor, roundQty, splitQuantityByPercentage, splitQuantityEvenly } from "@/lib/money";
import { addMonths, addWeeks, isPast, startOfDay } from "@/lib/dates";

/**
 * Delivery plans — the vendor's promised schedule, i.e. the PLANNED GRNs.
 *
 * Every vendor PO carries one. The PM is never made to build it by hand: a single
 * tranche for the full quantity on the PO's expected date is generated by default,
 * and the split helpers below back the "split into N" / "monthly" buttons.
 *
 * This is what the forecast is built from — without a plan there is nothing to forecast.
 */

export type PlanItemInput = {
  label?: string | null;
  plannedDate: Date;
  notes?: string | null;
  quantities: Array<{ vendorPoLineId: string; quantity: number }>;
};

export type PlanLineForSplit = {
  vendorPoLineId: string;
  quantity: number;
};

/** One tranche for everything, on the expected delivery date. The zero-effort default. */
export function generateDefaultPlan(lines: PlanLineForSplit[], plannedDate: Date): PlanItemInput[] {
  return [
    {
      label: "Full delivery",
      plannedDate: startOfDay(plannedDate),
      quantities: lines.map((line) => ({ vendorPoLineId: line.vendorPoLineId, quantity: roundQty(line.quantity) })),
    },
  ];
}

/**
 * N equal shipments, `intervalWeeks` apart. Rounding remainders land on the last
 * tranche so the plan always sums back to the ordered quantity.
 */
export function splitEvenly(
  lines: PlanLineForSplit[],
  parts: number,
  startDate: Date,
  intervalWeeks = 4,
): PlanItemInput[] {
  const safeParts = Math.max(1, Math.floor(parts));
  const perLine = lines.map((line) => splitQuantityEvenly(line.quantity, safeParts));

  return Array.from({ length: safeParts }, (_, index) => ({
    label: `Shipment ${index + 1} of ${safeParts}`,
    plannedDate: startOfDay(addWeeks(startDate, index * intervalWeeks)),
    quantities: lines.map((line, lineIndex) => ({
      vendorPoLineId: line.vendorPoLineId,
      quantity: perLine[lineIndex][index],
    })),
  }));
}

/** N equal shipments one month apart. */
export function splitMonthly(lines: PlanLineForSplit[], months: number, startDate: Date): PlanItemInput[] {
  const safeMonths = Math.max(1, Math.floor(months));
  const perLine = lines.map((line) => splitQuantityEvenly(line.quantity, safeMonths));

  return Array.from({ length: safeMonths }, (_, index) => ({
    label: `Month ${index + 1} of ${safeMonths}`,
    plannedDate: startOfDay(addMonths(startDate, index)),
    quantities: lines.map((line, lineIndex) => ({
      vendorPoLineId: line.vendorPoLineId,
      quantity: perLine[lineIndex][index],
    })),
  }));
}

/** Percentage split, e.g. 30/40/30 against milestone dates. */
export function splitByPercentage(
  lines: PlanLineForSplit[],
  tranches: Array<{ percentage: number; plannedDate: Date; label?: string }>,
): PlanItemInput[] {
  const perLine = lines.map((line) =>
    splitQuantityByPercentage(line.quantity, tranches.map((t) => t.percentage)),
  );

  return tranches.map((tranche, index) => ({
    label: tranche.label ?? `${tranche.percentage}%`,
    plannedDate: startOfDay(tranche.plannedDate),
    quantities: lines.map((line, lineIndex) => ({
      vendorPoLineId: line.vendorPoLineId,
      quantity: perLine[lineIndex][index],
    })),
  }));
}

/**
 * Planned quantity may never exceed what was ordered on the line.
 * `alreadyPlanned` carries tranches that already exist, so adding one more to a PO
 * is checked against the whole plan rather than just the new rows.
 */
export function assertPlanWithinOrdered(
  items: PlanItemInput[],
  orderedByLineId: Map<string, { quantity: number; description: string }>,
  alreadyPlanned: Map<string, number> = new Map(),
): void {
  const plannedByLine = new Map(alreadyPlanned);
  for (const item of items) {
    for (const entry of item.quantities) {
      if (entry.quantity <= 0) continue;
      plannedByLine.set(entry.vendorPoLineId, roundQty((plannedByLine.get(entry.vendorPoLineId) ?? 0) + entry.quantity));
    }
  }

  for (const [lineId, planned] of plannedByLine) {
    const ordered = orderedByLineId.get(lineId);
    if (!ordered) throw new Error("The delivery plan refers to a line that is not on this purchase order.");
    if (planned > ordered.quantity) {
      throw new Error(
        `Planned quantity for "${ordered.description}" (${planned}) is more than the ${ordered.quantity} ordered.`,
      );
    }
  }
}

/**
 * Replace a PO's plan wholesale. Only valid before anything has been received against
 * it — once receipts exist, tranches are edited individually so history stays intact.
 */
export async function replacePlan(vendorPoId: string, items: PlanItemInput[], db: Db = prisma): Promise<void> {
  const po = await db.vendorPO.findUnique({
    where: { id: vendorPoId },
    include: { lines: true, planItems: { include: { grns: { where: { status: "POSTED" }, select: { id: true } } } } },
  });
  if (!po) throw new Error("Purchase order not found.");

  const withReceipts = po.planItems.filter((item) => item.grns.length > 0);
  if (withReceipts.length > 0) {
    throw new Error("Deliveries have already been received against this plan — edit the individual tranches instead.");
  }

  const orderedByLineId = new Map(po.lines.map((line) => [line.id, { quantity: line.quantity, description: line.description }]));
  assertPlanWithinOrdered(items, orderedByLineId);

  await db.deliveryPlanItem.deleteMany({ where: { vendorPoId } });
  await createPlanItems(vendorPoId, items, db);
}

/**
 * The single write path for planned deliveries — so the "never plan more than was
 * ordered" rule is enforced here rather than by every caller remembering to check.
 */
export async function createPlanItems(vendorPoId: string, items: PlanItemInput[], db: Db = prisma): Promise<void> {
  const po = await db.vendorPO.findUnique({
    where: { id: vendorPoId },
    include: {
      lines: true,
      planItems: { where: { status: { not: "CANCELLED" } }, include: { lines: true } },
    },
  });
  if (!po) throw new Error("Purchase order not found.");

  const alreadyPlanned = new Map<string, number>();
  for (const item of po.planItems) {
    for (const line of item.lines) {
      alreadyPlanned.set(
        line.vendorPoLineId,
        roundQty((alreadyPlanned.get(line.vendorPoLineId) ?? 0) + line.plannedQuantity),
      );
    }
  }

  assertPlanWithinOrdered(
    items,
    new Map(po.lines.map((line) => [line.id, { quantity: line.quantity, description: line.description }])),
    alreadyPlanned,
  );

  // Sequence continues past cancelled tranches too — [vendorPoId, seq] is unique.
  const highestSeq = await db.deliveryPlanItem.aggregate({ where: { vendorPoId }, _max: { seq: true } });
  let seq = highestSeq._max.seq ?? 0;
  for (const item of items) {
    const quantities = item.quantities.filter((entry) => entry.quantity > 0);
    if (quantities.length === 0) continue;
    seq += 1;
    await db.deliveryPlanItem.create({
      data: {
        vendorPoId,
        seq,
        label: item.label ?? null,
        plannedDate: startOfDay(item.plannedDate),
        notes: item.notes ?? null,
        lines: {
          create: quantities.map((entry) => ({
            vendorPoLineId: entry.vendorPoLineId,
            plannedQuantity: roundQty(entry.quantity),
          })),
        },
      },
    });
  }
}

/** Accepted quantity received against one tranche, per PO line. */
export async function receivedByPlanItem(planItemId: string, db: Db = prisma): Promise<Map<string, number>> {
  const grnLines = await db.gRNLine.findMany({
    where: { grn: { deliveryPlanItemId: planItemId, status: "POSTED" } },
    select: { vendorPoLineId: true, quantityAccepted: true },
  });

  const received = new Map<string, number>();
  for (const line of grnLines) {
    received.set(line.vendorPoLineId, roundQty((received.get(line.vendorPoLineId) ?? 0) + line.quantityAccepted));
  }
  return received;
}

/**
 * PLANNED → PARTIAL → FULFILLED, derived from posted GRNs.
 * "Overdue" is deliberately not a status: it is computed at read time from the date.
 */
export async function recomputePlanItemStatus(planItemId: string, db: Db = prisma): Promise<void> {
  const item = await db.deliveryPlanItem.findUnique({
    where: { id: planItemId },
    include: { lines: true },
  });
  if (!item || item.status === "CANCELLED") return;

  const received = await receivedByPlanItem(planItemId, db);
  const totalPlanned = item.lines.reduce((sum, line) => sum + line.plannedQuantity, 0);
  const totalReceived = item.lines.reduce((sum, line) => sum + Math.min(received.get(line.vendorPoLineId) ?? 0, line.plannedQuantity), 0);

  let status: DeliveryPlanItemStatus = "PLANNED";
  if (totalReceived >= roundQty(totalPlanned) && totalPlanned > 0) status = "FULFILLED";
  else if (totalReceived > 0) status = "PARTIAL";

  if (status !== item.status) {
    await db.deliveryPlanItem.update({ where: { id: planItemId }, data: { status } });
  }
}

export async function updatePlanItem(
  planItemId: string,
  input: { plannedDate: Date; label: string | null; notes: string | null; quantities: Array<{ vendorPoLineId: string; quantity: number }> },
  db: Db = prisma,
): Promise<void> {
  const item = await db.deliveryPlanItem.findUnique({
    where: { id: planItemId },
    include: { vendorPo: { include: { lines: true } } },
  });
  if (!item) throw new Error("Planned delivery not found.");

  const received = await receivedByPlanItem(planItemId, db);
  for (const entry of input.quantities) {
    const already = received.get(entry.vendorPoLineId) ?? 0;
    if (entry.quantity < already) {
      throw new Error(`Planned quantity cannot be lower than the ${already} already received against this delivery.`);
    }
  }

  // Everything else on the PO stays as planned; only this tranche moves.
  const otherItems = await db.deliveryPlanItem.findMany({
    where: { vendorPoId: item.vendorPoId, id: { not: planItemId }, status: { not: "CANCELLED" } },
    include: { lines: true },
  });
  const proposed: PlanItemInput[] = [
    ...otherItems.map((other) => ({
      plannedDate: other.plannedDate,
      quantities: other.lines.map((line) => ({ vendorPoLineId: line.vendorPoLineId, quantity: line.plannedQuantity })),
    })),
    { plannedDate: input.plannedDate, quantities: input.quantities },
  ];
  assertPlanWithinOrdered(
    proposed,
    new Map(item.vendorPo.lines.map((line) => [line.id, { quantity: line.quantity, description: line.description }])),
  );

  await db.deliveryPlanLine.deleteMany({ where: { planItemId } });
  await db.deliveryPlanItem.update({
    where: { id: planItemId },
    data: {
      plannedDate: startOfDay(input.plannedDate),
      label: input.label,
      notes: input.notes,
      lines: {
        create: input.quantities
          .filter((entry) => entry.quantity > 0)
          .map((entry) => ({ vendorPoLineId: entry.vendorPoLineId, plannedQuantity: roundQty(entry.quantity) })),
      },
    },
  });
  await recomputePlanItemStatus(planItemId, db);
}

export async function cancelPlanItem(planItemId: string, db: Db = prisma): Promise<void> {
  const received = await receivedByPlanItem(planItemId, db);
  if ([...received.values()].some((qty) => qty > 0)) {
    throw new Error("This delivery has already been received and cannot be cancelled.");
  }
  await db.deliveryPlanItem.update({ where: { id: planItemId }, data: { status: "CANCELLED" } });
}

// ---------------------------------------------------------------- coverage & reads

export type LineCoverage = {
  vendorPoLineId: string;
  lineNo: number;
  description: string;
  uom: string;
  orderedQty: number;
  plannedQty: number;
  receivedQty: number;
  outstandingQty: number;
  unplannedQty: number;
  unitCostMinor: number;
};

/** Ordered vs. planned vs. received per PO line — the numbers on the PO detail page. */
export async function getPoCoverage(vendorPoId: string, db: Db = prisma): Promise<LineCoverage[]> {
  const po = await db.vendorPO.findUnique({
    where: { id: vendorPoId },
    include: {
      lines: {
        orderBy: { lineNo: "asc" },
        include: {
          planLines: { where: { planItem: { status: { not: "CANCELLED" } } } },
          grnLines: { where: { grn: { status: "POSTED" } } },
        },
      },
    },
  });
  if (!po) return [];

  return po.lines.map((line) => {
    const plannedQty = roundQty(line.planLines.reduce((sum, planLine) => sum + planLine.plannedQuantity, 0));
    const receivedQty = roundQty(line.grnLines.reduce((sum, grnLine) => sum + grnLine.quantityAccepted, 0));
    return {
      vendorPoLineId: line.id,
      lineNo: line.lineNo,
      description: line.description,
      uom: line.uom,
      orderedQty: roundQty(line.quantity),
      plannedQty,
      receivedQty,
      outstandingQty: roundQty(Math.max(0, line.quantity - receivedQty)),
      unplannedQty: roundQty(Math.max(0, line.quantity - plannedQty)),
      unitCostMinor: line.unitCostMinor,
    };
  });
}

export type PlanItemView = {
  id: string;
  seq: number;
  label: string | null;
  plannedDate: Date;
  status: DeliveryPlanItemStatus;
  isOverdue: boolean;
  notes: string | null;
  valueMinor: number;
  lines: Array<{
    vendorPoLineId: string;
    description: string;
    uom: string;
    plannedQuantity: number;
    receivedQuantity: number;
    outstandingQuantity: number;
  }>;
};

export async function getPlanForPo(vendorPoId: string, db: Db = prisma): Promise<PlanItemView[]> {
  const items = await db.deliveryPlanItem.findMany({
    where: { vendorPoId },
    include: {
      lines: { include: { vendorPoLine: true } },
      grns: { where: { status: "POSTED" }, include: { lines: true } },
    },
    orderBy: [{ plannedDate: "asc" }, { seq: "asc" }],
  });

  return items.map((item) => {
    const received = new Map<string, number>();
    for (const grn of item.grns) {
      for (const grnLine of grn.lines) {
        received.set(grnLine.vendorPoLineId, roundQty((received.get(grnLine.vendorPoLineId) ?? 0) + grnLine.quantityAccepted));
      }
    }

    const lines = item.lines.map((line) => {
      const receivedQuantity = received.get(line.vendorPoLineId) ?? 0;
      return {
        vendorPoLineId: line.vendorPoLineId,
        description: line.vendorPoLine.description,
        uom: line.vendorPoLine.uom,
        plannedQuantity: roundQty(line.plannedQuantity),
        receivedQuantity,
        outstandingQuantity: roundQty(Math.max(0, line.plannedQuantity - receivedQuantity)),
      };
    });

    const valueMinor = item.lines.reduce(
      (sum, line) => sum + lineTotalMinor(line.plannedQuantity, line.vendorPoLine.unitCostMinor),
      0,
    );

    return {
      id: item.id,
      seq: item.seq,
      label: item.label,
      plannedDate: item.plannedDate,
      status: item.status,
      isOverdue: item.status !== "FULFILLED" && item.status !== "CANCELLED" && isPast(item.plannedDate),
      notes: item.notes,
      valueMinor,
      lines,
    };
  });
}
